# Generated by Django 3.0.7 on 2020-06-17 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('value', models.FloatField()),
                ('ts', models.DateTimeField()),
            ],
            options={
                'db_table': 'measures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MeasureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='user friendly name')),
                ('description', models.CharField(max_length=2048, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='user friendly name')),
                ('description', models.CharField(max_length=2048, verbose_name='description')),
                ('probe_id', models.CharField(default='0x00', max_length=1024, verbose_name='unique ID of the probe')),
                ('unit', models.CharField(max_length=255, verbose_name='measurement unit')),
                ('unit_symbol', models.CharField(max_length=255, verbose_name='symbol for the unit')),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('measure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensors.MeasureType')),
            ],
        ),
    ]
