# Generated by Django 3.0.7 on 2020-06-17 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20200617_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(blank=True, max_length=2048, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='max_value',
            field=models.FloatField(null=True, verbose_name='max possible value'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='min_value',
            field=models.FloatField(null=True, verbose_name='min possible value'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='probe_id',
            field=models.CharField(blank=True, default='0x00', max_length=1024, verbose_name='unique ID of the probe'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit',
            field=models.CharField(blank=True, max_length=255, verbose_name='measurement unit'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit_symbol',
            field=models.CharField(blank=True, max_length=255, verbose_name='symbol for the unit'),
        ),
    ]
