# Generated by Django 3.0.7 on 2020-06-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_auto_20200617_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='highest possible value'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='min_value',
            field=models.FloatField(blank=True, null=True, verbose_name='lowest possible value'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='unit_symbol',
            field=models.CharField(blank=True, max_length=255, verbose_name='symbol of the unit'),
        ),
    ]
