# Generated by Django 3.0.7 on 2020-06-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0006_sensor_probe_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probedriver',
            name='name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='name of the driver'),
        ),
    ]
