# Generated by Django 3.0.7 on 2020-06-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0008_auto_20200617_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='unit_symbol',
        ),
        migrations.AddField(
            model_name='probedriver',
            name='max_value',
            field=models.FloatField(blank=True, null=True, verbose_name='highest possible value'),
        ),
        migrations.AddField(
            model_name='probedriver',
            name='min_value',
            field=models.FloatField(blank=True, null=True, verbose_name='lowest possible value'),
        ),
        migrations.AddField(
            model_name='probedriver',
            name='unit',
            field=models.CharField(blank=True, max_length=255, verbose_name='measurement unit'),
        ),
        migrations.AddField(
            model_name='probedriver',
            name='unit_symbol',
            field=models.CharField(blank=True, max_length=255, verbose_name='symbol of the unit'),
        ),
    ]
